# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        name: Use bun
        with:
          bun-version: latest
      - run: bun install
      - run: bun run generate
      - name: Packing
        run: zip ../a2a-app.zip *
        working-directory: .output/public
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .output/*.zip
          make_latest: true
          body_path: ./CHANGELOG.md
